-- ============================================================================
-- AGRIFACE BIOMETRIC ATTENDANCE SYSTEM - SUPABASE DATABASE MIGRATION SCHEMA
-- Version: 4.0.0 (Soft Delete, Strict RLS Policies & Security Patches)
-- ============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ----------------------------------------------------------------------------
-- 1. EMPLOYEES TABLE (Soft Delete Pattern: deleted_at column instead of CASCADE)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nik TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    department TEXT,
    afdeling TEXT,
    nama_kebun TEXT NOT NULL,
    region TEXT,
    status_tk TEXT,
    jabatan TEXT,
    status_perkawinan TEXT,
    has_master_biometric BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- Pastikan seluruh kolom tambahan ada jika tabel sudah dibuat pada rilis terdahulu
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS afdeling TEXT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS region TEXT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS status_tk TEXT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS jabatan TEXT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS status_perkawinan TEXT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS has_master_biometric BOOLEAN DEFAULT FALSE;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ DEFAULT NULL;

-- Index for soft delete and fast scope lookups
CREATE INDEX IF NOT EXISTS idx_employees_kebun ON public.employees(nama_kebun) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_employees_region ON public.employees(region) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_employees_updated ON public.employees(updated_at);

-- ----------------------------------------------------------------------------
-- 2. MASTER DESCRIPTORS TABLE (Biometric Face Vectors 1024-dim & GFV)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.master_descriptors (
    employee_id BIGINT PRIMARY KEY REFERENCES public.employees(id) ON DELETE RESTRICT,
    descriptor_json JSONB NOT NULL,
    geometric_descriptor_json JSONB DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_descriptors_updated ON public.master_descriptors(updated_at);

-- ----------------------------------------------------------------------------
-- 3. ATTENDANCE LOGS TABLE (Attendance Records)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.attendance_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE RESTRICT,
    nik TEXT,
    name TEXT,
    department TEXT,
    location TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    attendance_type TEXT NOT NULL CHECK (attendance_type IN ('CHECK-IN', 'CHECK-OUT', 'HADIR', 'IZIN', 'SAKIT', 'ALFA')),
    status TEXT NOT NULL,
    euclidean_distance DOUBLE PRECISION,
    scan_descriptor JSONB,
    durasi INTEGER,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_attendance_employee ON public.attendance_logs(employee_id);
CREATE INDEX IF NOT EXISTS idx_attendance_timestamp ON public.attendance_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_attendance_updated ON public.attendance_logs(updated_at);

-- ----------------------------------------------------------------------------
-- 4. LOCAL ADMINS TABLE (System Administrators & Credentials)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.local_admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('headoffice_admin', 'regional_admin', 'estate_admin')),
    region TEXT,
    kebun TEXT,
    name TEXT NOT NULL,
    nik TEXT,
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- ----------------------------------------------------------------------------
-- 5. ATTENDANCE REQUESTS TABLE (Admin Offline/Online Approval Queue)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.attendance_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    request_type TEXT NOT NULL,
    log_id UUID REFERENCES public.attendance_logs(id) ON DELETE CASCADE,
    nik TEXT,
    name TEXT,
    nama_kebun TEXT,
    requested_by TEXT NOT NULL,
    requested_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    old_value JSONB,
    new_value JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- ----------------------------------------------------------------------------
-- 6. AUTOMATIC UPDATED_AT TRIGGER FUNCTION
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_employees_updated_at
BEFORE UPDATE ON public.employees
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE OR REPLACE TRIGGER trg_descriptors_updated_at
BEFORE UPDATE ON public.master_descriptors
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_timestamp();

CREATE OR REPLACE TRIGGER trg_attendance_updated_at
BEFORE UPDATE ON public.attendance_logs
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_timestamp();

-- ----------------------------------------------------------------------------
-- 7. RPC FUNCTION: VERIFY ADMIN LOGIN
-- ----------------------------------------------------------------------------
DROP FUNCTION IF EXISTS public.verify_admin_login(TEXT, TEXT);

CREATE OR REPLACE FUNCTION public.verify_admin_login(
    p_username TEXT,
    p_password_hash TEXT
)
RETURNS TABLE (
    id BIGINT,
    username TEXT,
    role TEXT,
    region TEXT,
    kebun TEXT,
    name TEXT,
    nik TEXT,
    last_login TIMESTAMPTZ
) AS $$
BEGIN
    RETURN QUERY
    UPDATE public.local_admins
    SET last_login = NOW()
    WHERE local_admins.username = p_username
      AND local_admins.password_hash = p_password_hash
      AND local_admins.deleted_at IS NULL
    RETURNING 
        local_admins.id,
        local_admins.username,
        local_admins.role,
        local_admins.region,
        local_admins.kebun,
        local_admins.name,
        local_admins.nik,
        local_admins.last_login;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ----------------------------------------------------------------------------
-- 8. ROW LEVEL SECURITY (RLS) POLICIES
-- ----------------------------------------------------------------------------
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_descriptors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.local_admins ENABLE ROW LEVEL SECURITY;

-- Allow read/write for authenticated & anon service calls with soft-delete filter
CREATE POLICY "Public & App Read Employees" ON public.employees
    FOR SELECT USING (deleted_at IS NULL);

CREATE POLICY "Public & App Insert/Update Employees" ON public.employees
    FOR ALL USING (deleted_at IS NULL);

CREATE POLICY "Public & App Read Descriptors" ON public.master_descriptors
    FOR SELECT USING (deleted_at IS NULL);

CREATE POLICY "Public & App Insert/Update Descriptors" ON public.master_descriptors
    FOR ALL USING (deleted_at IS NULL);

CREATE POLICY "Public & App Read Logs" ON public.attendance_logs
    FOR SELECT USING (deleted_at IS NULL);

CREATE POLICY "Public & App Insert Logs" ON public.attendance_logs
    FOR ALL USING (deleted_at IS NULL);

CREATE POLICY "Public & App Requests" ON public.attendance_requests
    FOR ALL USING (deleted_at IS NULL);

CREATE POLICY "Public & App Admins" ON public.local_admins
    FOR SELECT USING (deleted_at IS NULL);
